
# docker exec -it psdb_test bash
# connection string
# postgres://root:secret@localhost:5432/testdb?sslmode=disable
services: 
  psdb_test:
    container_name: psdb_test
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
    ports: 
      - "5432:5432"
    volumes:
      - psql_data_test:/var/lib/postgresql/data
          
  adminer: 
    container_name: adminer
    image: adminer
    restart: always
    ports: 
      - 8080:8080
    depends_on: 
      - psdb_test

volumes: 
  psql_data_test:
#  psql_data_live:
