
services: 
  mongo1: 
    container_name: mongo1
    restart: unless-stopped
    image: mongo
    ports:
      - 27020:27017
    volumes:
      - mongo1-data:/data/db
      - ./rs-init.sh:/scripts/rs-init.sh
    networks:
      - mongoCluster
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    entrypoint: ["usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs"]
    links: 
      - mongo2
      - mongo3
  mongo2: 
    container_name: mongo2
    restart: unless-stopped
    image: mongo
    ports:
      - 27021:27017
    volumes:
      - mongo2-data:/data/db
    networks:
      - mongoCluster
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    entrypoint: ["usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs"]
  mongo3: 
    container_name: mongo3
    restart: unless-stopped
    image: mongo
    ports:
      - 27021:27017
    volumes:
      - mongo2-data:/data/db
    networks:
      - mongoCluster
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    entrypoint: ["usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs"]
  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports: 
      - 8081:8081
    environment: 
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  
volumes: 
  mongo-data:
  
networks:
  mongoCluster:

